version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass#123
    networks:
      - app-net
    volumes:
      - ./:/home/app
  dogs-api:
    build:
      args:
        user: 1000
        uid: 1000
      context: .
    working_dir: /home/app
    volumes:
      - ./:/home/app
    env_file:
      - .env
    ports:
      - 3500:3500
    depends_on:
      - mssql
    networks:
      - app-net
networks:
  app-net:
